[sphinx]
templates_path = ["_templates"]
master_doc = "index"
project = "IPython"
copyright = "The IPython Development Team"
github_project_url = "https://github.com/ipython/ipython"
source_suffix = ".rst"
exclude_patterns = ["**.ipynb_checkpoints"]
pygments_style = "sphinx"
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.inheritance_diagram",
    "sphinx.ext.intersphinx",
    "sphinx.ext.graphviz",
    "sphinxcontrib.jquery",
    "IPython.sphinxext.ipython_console_highlighting",
    "IPython.sphinxext.ipython_directive",
    "sphinx.ext.napoleon",  # to preprocess docstrings
    "github",  # for easy GitHub links
    "magics",
    "configtraits",
]
today_fmt = "%B %d, %Y"
default_role = "literal"
modindex_common_prefix = ["IPython."]

[sphinx.autodoc_type_aliases]
Matcher= " IPython.core.completer.Matcher"
MatcherAPIv1 = " IPython.core.completer.MatcherAPIv1"

[intersphinx_registry]
packages = [
    "python",
    "rpy2",
    "jupyterclient",
    "jupyter",
    "jedi",
    "traitlets",
    "ipykernel",
    "prompt_toolkit",
    "ipywidgets",
    "ipyparallel",
    "pip"
]

[html]
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_favicon = "_static/favicon.ico"
html_last_updated_fmt = "%b %d, %Y"
htmlhelp_basename = "ipythondoc"
html_additional_pages = [
    ["interactive/htmlnotebook", "notebook_redirect.html"],
    ["interactive/notebook", "notebook_redirect.html"],
    ["interactive/nbconvert", "notebook_redirect.html"],
    ["interactive/public_server", "notebook_redirect.html"]
]

[numpydoc]
numpydoc_show_class_members = false
numpydoc_class_members_toctree = false
warning_is_error = true

[latex]
latex_documents = [
    ['index', 'ipython.tex', 'IPython Documentation',
     'The IPython Development Team', 'manual', true],
    ['parallel/winhpc_index', 'winhpc_whitepaper.tex',
     'Using IPython on Windows HPC Server 2008',
     "Brian E. Granger", 'manual', true]
]
latex_use_modindex = true
latex_font_size = "11pt"
texinfo_documents = [
    [
        "index",
        "ipython",
        "IPython Documentation",
        "The IPython Development Team",
        "IPython",
        "IPython Documentation",
        "Programming",
        1,
    ]
]

