name: Run tests

on:
  push:
    branches:
      - main
      - master
      - '*.x'
  pull_request:
  # Run weekly on Monday at 1:23 UTC
  schedule:
  - cron:  '23 1 * * 1'
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]
        python-version: ["3.10"]
        deps: [test_extra]
        # Test all on ubuntu, test ends on macos

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install latex
      if: runner.os == 'Linux' && matrix.deps == 'test_extra'
      run: echo "disable latex for now, issues in mirros" #sudo apt-get -yq -o Acquire::Retries=3 --no-install-suggests --no-install-recommends install texlive dvipng
    - name: Install and update Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel build
        python -m pip install --upgrade -e .[${{ matrix.deps }}]
    - name: pytest
      env:
        COLUMNS: 120
      run: |
        pytest --color=yes -raXxs
